#!/bin/sh

PREFIX="/usr/local/bin"

INSTALL() {
	cp cch.pl $PREFIX/cch
	printf '%s\n' "cch installed"
}

UNINSTALL() {
	rm $PREFIX/cch
	printf '%s\n' "cch removed"
}

[ -n "$1" ] || exit
[ "$1" = "install" ] && INSTALL
[ "$1" = "uninstall" ] && UNINSTALL
